import {
  Bell,
  BookOpen,
  Calendar,
  Car,
  ClipboardList,
  CreditCard,
  FileText,
  KeyRound,
  Layers,
  MessageSquare,
  Settings,
  Shield,
  Star,
  Tags,
  Truck,
  UserCog,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

export const iconMap = {
  users: Users,
  admins: UserCog,
  providers: Truck,
  services: Wrench,
  vehicles: Car,
  maintenancerecords: ClipboardList,
  vehiclereminders: Calendar,
  bookingdocuments: BookOpen,
  orders: ClipboardList,
  wallets: Wallet,
  transactions: CreditCard,
  subscription_plans: Tags,
  user_subscriptions: Shield,
  subscriptions: Layers,
  chats: MessageSquare,
  messages: MessageSquare,
  notifications: Bell,
  reviews: Star,
  settings: Settings,
  pending_registrations: FileText,
  logouts: KeyRound,
  promocodes: Tags,
};
